# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "test-terragrunt-state"
    encrypt = true
    key     = "./terraform.tfstate"
    profile = "dev-env"
    region  = "eu-central-1"
  }
}
