# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "rasim-test-terragrunt-state"
    encrypt = true
    key     = "./terraform.tfstate"
    profile = "sufle-dev"
    region  = "eu-central-1"
  }
}
